# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_forr1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forr1',
            options={'managed': True},
        ),
    ]
