# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20160426_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='forr',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='forr1',
            name='index',
        ),
        migrations.AlterField(
            model_name='forr1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
